AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  Cloud Assignment 2
  

Resources:
#Lambda Functions
  CloudAssignemnt2Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CloudAssignemnt2Function-Somya
      CodeUri: CloudAssignemnt2Function/
      Description: Lambda for Cloud Assignemnt2
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Environment:
        Variables:
          SenderMail: somya@antstack.io
      Policies: 
      - Statement:
        - Effect: Allow
          Action: ses:SendEmail
          Resource: arn:aws:ses:ap-south-1:873102235883:identity/somya@antstack.io
      
#API
  CloudAssignment2API:
    Type: AWS::Serverless::Api
    Properties:
      Name: CloudAssignment2API-Somya
      StageName: Dev
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: CloudAssignment2API/swagger.yaml
      
#SNS
  CloudAssignment2SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !GetAtt CloudAssignemnt2Function.Arn
          Protocol: "lambda"
      TopicName: CloudAssignment2SNSTopic

#Role
  CloudAssignment1Role:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: MySNSolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - sns:*
                Resource:
                  - !Ref CloudAssignment2SNSTopic

#Permission
  LambdaSNSPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt CloudAssignemnt2Function.Arn
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref CloudAssignment2SNSTopic       
